#!/bin/bash
BIND=127.0.0.1:9000  ## php-cgi daemon ip/port to listen on (must be same as nginx config).
USER=www-data  ## your user for nginx workers (default is www-data).
PHP_FCGI_CHILDREN=1  ##  number of children processes to run (should be less then nginx processes).
PHP_FCGI_MAX_REQUESTS=500 ## default is 1000, this is useful for big traffic sites.

PHP_CGI=/usr/bin/php-cgi
PHP_CGI_NAME=`basename $PHP_CGI`
PHP_CGI_ARGS="- USER=$USER PATH=/usr/bin PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS $PHP_CGI -b $BIND"
RETVAL=0

start() {
  echo -n "Starting PHP FastCGI: "
  start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env -- $PHP_CGI_ARGS
  RETVAL=$?
  echo "$PHP_CGI_NAME."
}

stop() {
  echo -n "Stopping PHP FastCGI: "
  killall -q -w -u $USER $PHP_CGI
  RETVAL=$?
  echo "$PHP_CGI_NAME."
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) stop start;;
  *) echo "Usage: php-fastcgi {start|stop|restart}" exit 1 ;;
esac
exit $RETVAL

